#!/bin/sh
# Name: Weather Installer
# DontUseFBInk
# Author: Eric Morrison
# Description: Install the standalone weather display and open ZIP setup.
# Generated by build_installer.py; MIT licensed. Dependencies retain licenses.

PAYLOAD_SHA256=__PAYLOAD_SHA256__
INSTALL_ROOT=/mnt/us
STAGE=
FBINK=/mnt/us/libkh/bin/fbink

error() {
    printf 'Weather installer: %s\n' "$*" >&2
    if [ -d "$INSTALL_ROOT/documents" ]; then
        printf 'Weather installation stopped:\n%s\n' "$*" > "$INSTALL_ROOT/documents/Weather installation error.txt"
    fi
    [ ! -x "$FBINK" ] || "$FBINK" -c -m -y 5 "Weather installation stopped.

$*

See Weather installation error in the Library." >/dev/null 2>&1
    return 1
}

cleanup() { [ -z "$STAGE" ] || rm -rf "$STAGE"; }

supported_model() { printf '%s\n' "$1" | grep -Fq "deviceName='PaperWhite 3';"; }

unpack_payload() {
    payload_line=$(awk '/^__WEATHER_PAYLOAD__$/ {print NR; exit}' "$1")
    [ -n "$payload_line" ] || { error 'Installer payload is missing.'; return 1; }
    tail -n "+$((payload_line + 1))" "$1" | base64 -d > "$2/package.tar.gz" || \
        { error 'Installer payload is damaged. Download it again.'; return 1; }
    actual=$(sha256sum "$2/package.tar.gz" | awk '{print $1}')
    [ "$actual" = "$PAYLOAD_SHA256" ] || { error 'Installer verification failed. Download it again.'; return 1; }
    tar -xzf "$2/package.tar.gz" -C "$2" || { error 'Cannot unpack the installer.'; return 1; }
}

main() {
    # Never run the payload or write Kindle paths on the setup computer.
    [ "$(uname -s)" = Linux ] && [ "$(uname -m)" = armv7l ] && [ "$(id -u)" = 0 ] || \
        { printf 'Copy this file to documents on a jailbroken Kindle and open it from the Library.\n' >&2; return 1; }
    grep -Eq '(^|[^0-9.])5\.16\.2\.1\.1([^0-9.]|$)' /etc/prettyversion.txt && \
    grep -q 'max77696-onkey' /proc/bus/input/devices || \
        { error 'Requires Paperwhite 3 with firmware 5.16.2.1.1.'; return 1; }
    [ ! -e /usr/bin/otaupd ] && [ -f /usr/bin/otaupd.bck ] && [ ! -e /usr/bin/otav3 ] || \
        { error 'Block firmware updates using the jailbreak guide first.'; return 1; }
    [ -x "$FBINK" ] || { error 'FBInk is missing. Complete jailbreak setup first.'; return 1; }
    device_info=$("$FBINK" -e 2>&1) || { error 'Cannot identify the screen hardware.'; return 1; }
    supported_model "$device_info" || \
        { error 'This installer supports Paperwhite 3 only.'; return 1; }
    "$FBINK" --help 2>&1 | grep -q 'truetype' || { error 'FBInk needs TrueType support.'; return 1; }
    # The keyboard is an independently installed dependency, never bundled.
    for path in extensions extensions/kterm; do
        [ ! -L "$INSTALL_ROOT/$path" ] || { error 'The keyboard path is a symbolic link; left unchanged.'; return 1; }
    done
    [ -x "$INSTALL_ROOT/extensions/kterm/bin/kterm" ] && \
    [ -f "$INSTALL_ROOT/extensions/kterm/layouts/keyboard-300dpi.xml" ] && \
    [ -d "$INSTALL_ROOT/extensions/kterm/vte/terminfo" ] || \
        { error 'Install official kTerm 2.6 first. See the Kindle Weather README on GitHub.'; return 1; }
    for tool in mktemp base64 sha256sum tar awk tail cp mv cmp tr grep du df; do
        command -v "$tool" >/dev/null 2>&1 || { error "Missing installation tool: $tool"; return 1; }
    done
    free_kb=$(df -Pk "$INSTALL_ROOT" | awk 'END {print $4}')
    state_kb=0
    [ ! -d "$INSTALL_ROOT/weather/state" ] || state_kb=$(du -sk "$INSTALL_ROOT/weather/state" | awk '{print $1}')
    case "$free_kb:$state_kb" in *[!0-9:]*|:*|*:) error 'Cannot read available storage.'; return 1 ;; esac
    [ "$free_kb" -ge "$((state_kb + 16384))" ] || { error 'Free at least 16 MB plus room for your saved weather state.'; return 1; }
    STAGE=$(mktemp -d "$INSTALL_ROOT/.weather-installer.XXXXXX") || return 1
    trap cleanup EXIT
    trap 'exit 1' HUP INT TERM
    unpack_payload "$0" "$STAGE" || return 1
    if [ -f /etc/upstart/paperwhite-weather.conf ] && \
       ! cmp -s /etc/upstart/paperwhite-weather.conf "$STAGE/weather/paperwhite-weather.conf"; then
        error 'A different Weather startup job already exists; left unchanged.'; return 1
    fi
    export TERM=xterm TERMINFO="$INSTALL_ROOT/extensions/kterm/vte/terminfo"
    "$INSTALL_ROOT/extensions/kterm/bin/kterm" -l "$INSTALL_ROOT/extensions/kterm/layouts/keyboard-300dpi.xml" \
        -c 0 -k 1 -s 16 -e "/bin/sh '$STAGE/install.sh' --confirm '$INSTALL_ROOT' '$STAGE'" || return 1
    [ "$(cat "$STAGE/result" 2>/dev/null)" = installed ] || return 0
    cleanup
    STAGE=
    trap - EXIT HUP INT TERM
    exec /bin/sh "$INSTALL_ROOT/weather/runtime.sh" start
}

main
exit $?
__WEATHER_PAYLOAD__
